config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :locations

  resources :places do
    resources :likes
  end
  root 'places#index'

  namespace :admin do
    resources :places, except: :create
    resources :users, except: :create
    # get 'users' => 'users#index'
    # get 'users/edit'
    # get 'users/update'
    # get 'users/delete'
    # get 'places' => 'places#index'
    # get 'places/edit'
    # get 'places/update'
    # get 'places/delete'
  end
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  include PgSearch::Model
  scope :sorted, -> { order(name: :asc) }
  # pg_search_scope :search_by_name, :against => [:name]
  # pg_search_scope :search_by_category, :against => [:category]

  pg_search_scope :search,
                  against: %i[
                    name
                    category
                  ],
                  using: {
                    tsearch: {
                      prefix: true,
                      normalization: 2
                    }
                  }

  has_many :likes
  has_many :users, through: :likes
  has_many :locations, through: :users

  has_one_attached :photo

  def self.perform_search(keyword)
    if keyword.present?
    then Place.search(keyword)
    else
      Place.all
    end.sorted
  end

  def locations
    users.map(&:locations).flatten
  end

  def cities
    locations.map(&:city)
  end

  def states
    locations.map(&:state)
  end

  def countries
    locations.map(&:country)
  end
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @places = Place.all
  end

  def edit
    @place = Place.find(params[:id])
    @likes = @place.likes
  end

  def show
    @place = Place.find(params[:id])
    @likes = @place.likes
    @users = User.all
    @locations = @users.map(&:locations).flatten
    @frequency = location_frequency(@locations)
    @likes_by_cities = likes_by(:city)
    @likes_by_states = likes_by(:state)
    @likes_by_countries = likes_by(:country)
  end

  def create
    #   Place.find_or_create_by(
    #   name: params[:place][:name],
    #   address: params[:place][:address],
    #   phone_number: params[:place][:phone_number],
    #   category: params[:place][:category]
    #   )
    redirect_to admin_places_path
  end

  def delete
    @place = Place.find(params[:id])
    @place.destroy
    flash[:success] = 'Place deleted'
    redirect_to admin_places_path
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    flash[:success] = 'Place deleted'
    redirect_to admin_places_path
  end

  def location_frequency(locations)
    {}.tap do |locations_by_frequency|
      locations.each do |location|
        location_city = location.city.to_s
        location_state = location.state.to_s
        location_country = location.country.to_s

        location_name = "#{location.city}, #{location.state} #{location.country}"
        if locations_by_frequency[location_city]
          locations_by_frequency[location_city] += 1
        else
          locations_by_frequency[location_city] = 1
        end
        if locations_by_frequency[location_state]
          locations_by_frequency[location_state] += 1
        else
          locations_by_frequency[location_state] = 1
        end
        if locations_by_frequency[location_country]
          locations_by_frequency[location_country] += 1
        else
          locations_by_frequency[location_country] = 1
        end
      end
    end
  end

  private

  def likes_by(geography)
    @place.locations.group_by(&geography).map do |group, locations|
      next if group.blank?

      {
        name: group,
        likes: locations.count
      }
    end.compact.sort_by do |group|
      group[:likes]
    end.reverse
  end

  def authenticate_admin!
    authenticate_user!
    redirect_to root_path, status: :forbidden unless current_user.admin?
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: %i[create edit update]

  def index
    @places = if params[:search].present?
                Place.perform_search(params[:search])
              else
                Place.all.order(name: :asc)
              end
    @place = Place.new
  end

  def show
    @place = Place.find(params[:id])
    @likes = @place.likes
    @users = User.all
    @locations = @users.map(&:locations).flatten
    # @frequency = location_frequency(@locations)
    @likes_by_cities = likes_by(:city)
    @likes_by_states = likes_by(:state)
    @likes_by_countries = likes_by(:country)
  end

  def likes
    @place = Place.find(params[:id])
    @likes = @place.likes
    @likes_by_cities = likes_by(:city)
    @likes_by_states = likes_by(:state)
    @likes_by_countries = likes_by(:country)
  end

  def update; end

  def edit; end

  def new
    @place = Place.new
  end

  def create
    if already_added?
      flash[:notice] = 'This restaurant has already been added!'
    else
      Place.find_or_create_by(
        name: params[:place][:name],
        address: params[:place][:address],
        phone_number: params[:place][:phone_number],
        category: params[:place][:category]
      )
      flash[:notice] = 'You have successfully added this restaurant to Food Mapp!'
    end
    redirect_to places_path
  end

  # def location_frequency(locations)
  #   {}.tap do |locations_by_frequency|
  #     locations.each do |location|
  #       location_city = "#{location.city}"
  #       location_state = "#{location.state}"
  #       location_country = "#{location.country}"

  #        location_name = "#{location.city}, #{location.state} #{location.country}"
  #         if locations_by_frequency[location_city]
  #          locations_by_frequency[location_city] += 1
  #         else
  #          locations_by_frequency[location_city]= 1
  #         end
  #         if locations_by_frequency[location_state]
  #          locations_by_frequency[location_state] += 1
  #         else
  #          locations_by_frequency[location_state]= 1
  #         end
  #         if locations_by_frequency[location_country]
  #          locations_by_frequency[location_country] += 1
  #         else
  #          locations_by_frequency[location_country]= 1
  #         end
  #     end
  #   end
  # end

  private

  def already_added?
    Place.where(id: params[:id]).exists?
  end

  def likes_by(geography)
    @place.locations.group_by(&geography).map do |group, locations|
      next if group.blank?

      {
        name: group,
        likes: locations.count
      }
    end.compact.sort_by do |group|
      group[:likes]
    end.reverse
  end
end

app/helpers/admin/places_helper.rb
module Admin::PlacesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/admin/places/edit.html.erb
<div class="c-section">
  <h1 class="c-title c-title--large"><%= @place.name %></h1>
  <h2 class="c-title"><%= @place.address %></h2>
  <h2 class="c-title"><%= @place.phone_number %></h2>
  <h2 class="c-title">Type of Restaurant: <%= @place.category %></h2>
  <h2 class="c-title c-title--tiny"># of Likes = <%= @place.likes.count %></h2>
  <h3 class="c-title c-title--tiny">Likes by Locations:</h3>
  <h3 class="c-title c-title--tiny">Cities: </h3>
  <h3 class="c-title c-title--tiny"># of cities = <%= @place.cities.uniq.reject(&:blank?).count %></h3>
  <h3 class="c-title c-title--tiny">List of cities: <%= @place.cities.uniq.reject(&:blank?).to_sentence %></h3>
  <h3 class="c-title c-title--tiny">States:</h3>
  <h3 class="c-title c-title--tiny"># of states = <%= @place.states.compact.uniq.reject(&:blank?).count %></h3>
  <h3 class="c-title c-title--tiny">List of states: <%= @place.states.uniq.reject(&:blank?).to_sentence %></h3>
  <h3 class="c-title c-title--tiny">Countries:</h3>
  <h3 class="c-title c-title--tiny"># of countries = <%= @place.countries.uniq.reject(&:blank?).count %></h3>
  <h3 class="c-title c-title--tiny">List of countries: <%= @place.countries.uniq.reject(&:blank?).to_sentence %></h3>
  <%# link_to "Purchase", new_book_sale_path(@book), class: "c-button c-button--focal" %>
</div>

app/views/admin/places/index.html.erb
<div class="c-section">
  <h1 class="display-5">Search for Restaurants</h1>
  <form class= "form-inline">
    <label class="sr-only" for="inlineFormInputGroup">Restaurant Search</label>
    <div class="input-group mb-2 mr-sm-2 mb-sm-0">
      <%= form_tag(places_path, method: "get") do %>
        <%= text_field_tag :search, nil, placeholder: "Search by name or category and press Enter", class: "form-control", style: "width: 25%;" %>
        <%= submit_tag "", style: "display: none; width: 25%;" %>
        <button type="submit" class="btn btn-dark"><%= submit_tag "", style: "display: none;" %>Search</button>
      <% end %>
    </div>
  </form>
</div>
<div class="card">
  <!-- <img class="card-img-top" src="/images/bootstrap-themes/card.png" alt="Card image cap"> -->
  <div class="card-body">
    <% @places.each do |place| %>
    <h1 class="display-4 text-chicle"><%= place.name %></h1>
    <h4><%= place.address %></h4>
    <h4><%= place.phone_number %></h4>
    <h4>Category: <%= place.category %></h4>
    <h4>Total Likes = <%= place.likes.count %><%= (place.likes.count) == 1 ? 'Like' : 'Likes'%></h4>
    <h4> <%# place.locations %></h4>
    <%# image_tag place.image.variant(resize: "200x300") %>
    <a><%= link_to "More Info", admin_place_path(place), class: "btn btn-dark btn-lg"%></a><br><br>
    <a><%= link_to 'Delete', admin_places_path, method: :destroy, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-lg"%></a><br><br><br>
    <% end %>
  </div>
</div>
<nav aria-label="...">
  <ul class="pagination">
    <li class="page-item disabled">
      <span class="page-link">Previous</span>
    </li>
    <li class="page-item">
      <a class="page-link" href="#!">1</a>
    </li>
    <li class="page-item active">
      <span class="page-link">
        2
        <span class="sr-only">(current)</span>
      </span>
    </li>
    <li class="page-item">
      <a class="page-link" href="#!">3</a>
    </li>
    <li class="page-item">
      <a class="page-link" href="#!">Next</a>
    </li>
  </ul>
</nav>

app/views/admin/places/show.html.erb
<div class="jumbotron">
  <div class="map_container">
    <div id="show_map"></div>
  </div>
  <h1 class="display-4 text-chicle"><%= @place.name %></h1>
  <h4><%= @place.address %></h4>
  <h4><%= @place.phone_number %></h4>
  <h4>Type of Restaurant: <%= @place.category %></h4>
  <h4># of Likes Received by Users = <%= @place.likes.count %></h4>
  <!-- <div class="map_container">
    <div id="likes_map"></div>
  </div> -->
  <h3>Likes by Cities</h3>
  <ol>
    <% @likes_by_cities.each do |group| %>
      <li><%= "#{group[:name]} = #{group[:likes]} Likes" %></li>
    <% end %>
  </ol>
  <h3>Likes by States</h3>
  <ol>
    <% @likes_by_states.each do |group| %>
      <li><%= "#{group[:name]} = #{group[:likes]} Likes" %></li>
    <% end %>
  </ol>
  <h3>Likes by Countries</h3>
  <ol>
    <% @likes_by_countries.each do |group| %>
      <li><%= "#{group[:name]} = #{group[:likes]} Likes" %></li>
    <% end %>
  </ol>
  <a><%= link_to 'Delete', admin_places_path, method: :destroy, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-lg"%></a>
</div>
<script>
  var place = <%== {lat: @place.latitude, lng: @place.longitude }.to_json %>;
  
  var map;

  function initMap() {
    map = new google.maps.Map(document.getElementById('show_map'), {
      center: {lat: place.latitude, lng: place.longitude},
      zoom: 12
    });

    // var position = new google.maps.LatLng(place.lat, place.lng);
    // var marker = new google.maps.Marker({
    //   position: position,
    //   map: map
    // });

    // places.forEach(function(place) {
    //   var position = new google.maps.LatLng(place.lat, place.lng);
    //   var marker = new google.maps.Marker({
    //     position: position,
    //     map: map
    //   });
    // });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDUbWRtQWZ3pC8radEZuKVryQ8A2dlayQw&callback=initMap" async defer></script>