config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :locations

  resources :places do
    resources :likes
  end
  root 'places#index'

  namespace :admin do
    resources :places, except: :create
    resources :users, except: :create
    # get 'users' => 'users#index'
    # get 'users/edit'
    # get 'users/update'
    # get 'users/delete'
    # get 'places' => 'places#index'
    # get 'places/edit'
    # get 'places/update'
    # get 'places/delete'
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes
  has_many :places, through: :likes

  has_many :user_locations
  has_many :locations, through: :user_locations

  has_one_attached :avatar

  accepts_nested_attributes_for :locations
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @likes = @user.likes
    @places = @user.places
    @locations = @user.locations
  end

  def update
    @post = Place.find(params[:id])
    @place.update(place_params)
    if @place.save
      redirect_to admin_places_path
    else
      render :edit
    end
  end

  def delete
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'User deleted'
    redirect_to admin_users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'User deleted'
    redirect_to admin_users_path
  end

  private

  def authenticate_admin!
    authenticate_user!
    redirect_to root_path, status: :forbidden unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @likes = @user.likes
    @locations = @user.locations
    @places = @user.places
  end

  def edit
    @user = current_user
    @likes = @user.likes
    @locations = @user.locations
  end

  def update
    @user = current_user
    @locations = @user.locations
    @user.update_attributes(user_params)

    if current_user.save
      redirect_to user_path
    else
      render :edit
    end
  end

  def delete
    @user = current_user
    @user.destroy
    flash[:success] = 'User deleted'
    redirect_to places_path
  end

  def destroy
    @user = current_user
    @user.destroy
    flash[:success] = 'User deleted'
    redirect_to places_path
  end

  private

  def user_params
    params
      .require(:user).permit(:name, locations_attributes: %i[city state country])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_location_fields.html.erb
<div class= "nested-fields">
  <div class= "form-inline border-dark">
    <%= f.input :city, label: 'City:  ' %>
    <%= f.input :state, label: 'State: ' %>
    <%= f.input :country, label: 'County: ' %>
    <%= link_to_remove_association "Remove Location", f %>
  </div>
</div>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/edit.html.erb
<div class= "jumbotron">
  <h1 class= "display-4 text-chicle text-primary">Step #2</h1>
  <h1 class= "display-5 text-chicle text-primary">Please enter a user name and locations where you have lived!</h1>
  <div class="card mb-3 border-0 ml-0 mr-0 mb-0 float-left">
    <div class="card-body">
      <%= simple_form_for @user do |f| %>
        <%= f.input :name, label: "Your name:" %><br><br>
        <!-- <h4>Upload you profile picture: <%# f.file_field :avatar %></h4><br><br> -->
        <div class= "locations">
          <%= f.simple_fields_for :locations do |location| %>
            <%= render "location_fields", f: location %>
          <% end %>
        </div>
        <div>
          <a><%= link_to_add_association 'Add Location', f, :locations, data: { association_insertion_node: ".locations", association_insertion_method: :append } %></a><br><br>
          <a><%= f.button :submit, "Update your profile", class: "btn btn-danger" %></a>
        </div>
      <% end %>
    </div>
  </div>
  <!-- <div class= "card border-0 float-right shadow mt-50">
    <div class= "card-body">
      <%# image_tag "christine-roy-343235-unsplash.jpg", size: "700x400" %>
    </div>
  </div> -->
</div>

app/views/users/show.html.erb
<div class= "container">
  <div class="row">
    <div class="col-sm-6">
      <div class="card border-0 clearfix m-0">
        <div class="card-body mt-0">
          <h1 class= "display-4 text-chicle text-primary ml-0"><%= current_user.name %>'s Profile Page</h1>
          <h2 class= "display-6">User Name: <%= current_user.name %></h2>
          <h2 class= "display-6">Email Address: <%= current_user.email %></h2>
          <% if current_user.avatar.attached? %>
            <h4 class= "nav_avatar"><%= image_tag current_user.avatar.variant(resize: "150 x 200"), class: "rounded-circle" %></h4>
            <a><%= link_to "Download Photo", rails_blob_path(current_user.avatar, disposition: "attachment"), class: "btn btn-dark" %></a>
          <% end %>
          <a><%= link_to "Edit Profile", edit_user_path(current_user), class: "btn btn-danger" %></a>
          <a><%= link_to "Change Email or Password", edit_user_registration_path(current_user), class: "btn btn-danger" %></a>
          <!-- <a><%# link_to 'Delete Profile', registration_path(current_user), method: :destroy, data: { confirm: 'Are you sure?' }, class: "btn btn-danger mt-3"%></a><br><br> -->
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card border-0 clearfix m-0">
        <div class="card-body mt-0">
          <h1 class= "text-chicle">Locations Where You've lived</h1>
            <ul class= "list-unstyled">
            <% @locations.each do |location| %>
              <h4><li><%= location.city %>, <%= location.state %> <%= location.country %></li></h4>
            <% end %>
            </ul>
          <h1 class= "text-chicle">Restaurants You've Liked</h1>
            <ul class= "list-unstyled">
            <% @places.each do |place| %>
              <h4><li><%= place.name %></li></h4>
            <% end %>
            </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>