config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :locations

  resources :places do
    resources :likes
  end
  root 'places#index'

  namespace :admin do
    resources :places, except: :create
    resources :users, except: :create
    # get 'users' => 'users#index'
    # get 'users/edit'
    # get 'users/update'
    # get 'users/delete'
    # get 'places' => 'places#index'
    # get 'places/edit'
    # get 'places/update'
    # get 'places/delete'
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes
  has_many :places, through: :likes

  has_many :user_locations
  has_many :locations, through: :user_locations

  has_one_attached :avatar

  accepts_nested_attributes_for :locations
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @likes = @user.likes
    @places = @user.places
    @locations = @user.locations
  end

  def update
    @post = Place.find(params[:id])
    @place.update(place_params)
    if @place.save
      redirect_to admin_places_path
    else
      render :edit
    end
  end

  def delete
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'User deleted'
    redirect_to admin_users_path
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = 'User deleted'
    redirect_to admin_users_path
  end

  private

  def authenticate_admin!
    authenticate_user!
    redirect_to root_path, status: :forbidden unless current_user.admin?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @likes = @user.likes
    @locations = @user.locations
    @places = @user.places
  end

  def edit
    @user = current_user
    @likes = @user.likes
    @locations = @user.locations
  end

  def update
    @user = current_user
    @locations = @user.locations
    @user.update_attributes(user_params)

    if current_user.save
      redirect_to user_path
    else
      render :edit
    end
  end

  def delete
    @user = current_user
    @user.destroy
    flash[:success] = 'User deleted'
    redirect_to places_path
  end

  def destroy
    @user = current_user
    @user.destroy
    flash[:success] = 'User deleted'
    redirect_to places_path
  end

  private

  def user_params
    params
      .require(:user).permit(:name, locations_attributes: %i[city state country])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="c-section">
  <h1 class="c-title c-title--large"><%= @user.name %></h1>
  <h2 class="c-title"><%= @user.email %></h2>
  <h2 class="c-title c-title--tiny"># of Likes = <%= @user.likes.count %></h2>
  <h3 class="c-title c-title--tiny">Locations:</h3>
  <h3 class="c-title c-title--tiny">Cities: </h3>
  <h3 class="c-title c-title--tiny">List of cities: <%= @user.cities.uniq.reject(&:blank?).to_sentence %></h3>
  <h3 class="c-title c-title--tiny">States:</h3>
  <h3 class="c-title c-title--tiny">List of states: <%= @user.states.uniq.reject(&:blank?).to_sentence %></h3>
  <h3 class="c-title c-title--tiny">Countries:</h3>
  <h3 class="c-title c-title--tiny">List of countries: <%= @user.countries.uniq.reject(&:blank?).to_sentence %></h3>
</div>

app/views/admin/users/index.html.erb
<div class="c-section">
  <% @users.each do |user| %>
    <div class="c-card u-margin-bottom-small">
      <div class="c-section">
        <% if user.avatar.attached? %>
        <h4><%= image_tag user.avatar.variant(resize: "150 x 200")%></h4>
        <% end %>
        <h2 class="c-title"><%= user.name %></h2>
        <h3 class="c-title c-title--tiny"><%= user.email %></h3>
        <h4 class="c-title c-title--tiny"><%# user.phone_number %></h4>
        <h4 class="c-title c-title--tiny"># of Likes = <%= user.likes.count %></h4>
        <h4 class="c-title c-title--tiny"> <%# place.locations %></h4>
        <button><%= link_to "More Info", admin_user_path(user), class: "c-button c-button--small c-button--focal"%></button>
        <button><%= link_to 'Delete', admin_users_path, method: :destroy, data: { confirm: 'Are you sure?' }, class: "c-button c-button--warning"%></button>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/users/show.html.erb
<div class="c-card u-margin-bottom-small">
  <div class="c-section">
    <% if @user.avatar.attached? %>
      <h4><%= image_tag @user.avatar.variant(resize: "150 x 200")%></h4>
    <% end %>
    <h2 class="c-title"><%= @user.name %></h2>
    <h3 class="c-title c-title--tiny"><%= @user.email %></h3>
    <h4 class="c-title c-title--tiny">Locations:</h4>
      <ul>
      <% @locations.each do |location| %>
        <li><%= location.city%>, <%= location.state %> <%= location.country %></li>
      <% end %>
      </ul>
    <h4 class="c-title c-title--tiny"># of Likes = <%= @user.likes.count %></h4>
    <h4 class="c-title c-title--tiny">Places Liked:</h4>
      <ul>
      <% @places.each do |place| %>
        <li><%= place.name %></li>
      <% end %>
      </ul>
    <button><%= link_to 'Delete', admin_users_path, method: :destroy, data: { confirm: 'Are you sure?' }, class: "c-button c-button--warning"%></button>
  </div>
</div>

app/views/admin/users/update,.html.erb
<h1>Admin::Users#update,</h1>
<p>Find me in app/views/admin/users/update,.html.erb</p>