config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :locations

  resources :places do
    resources :likes
  end
  root 'places#index'

  namespace :admin do
    resources :places, except: :create
    resources :users, except: :create
    # get 'users' => 'users#index'
    # get 'users/edit'
    # get 'users/update'
    # get 'users/delete'
    # get 'places' => 'places#index'
    # get 'places/edit'
    # get 'places/update'
    # get 'places/delete'
  end
end

app/models/place.rb
class Place < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
  include PgSearch::Model
  scope :sorted, -> { order(name: :asc) }
  # pg_search_scope :search_by_name, :against => [:name]
  # pg_search_scope :search_by_category, :against => [:category]

  pg_search_scope :search,
                  against: %i[
                    name
                    category
                  ],
                  using: {
                    tsearch: {
                      prefix: true,
                      normalization: 2
                    }
                  }

  has_many :likes
  has_many :users, through: :likes
  has_many :locations, through: :users

  has_one_attached :photo

  def self.perform_search(keyword)
    if keyword.present?
    then Place.search(keyword)
    else
      Place.all
    end.sorted
  end

  def locations
    users.map(&:locations).flatten
  end

  def cities
    locations.map(&:city)
  end

  def states
    locations.map(&:state)
  end

  def countries
    locations.map(&:country)
  end
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < ApplicationController
  before_action :authenticate_admin!
  def index
    @places = Place.all
  end

  def edit
    @place = Place.find(params[:id])
    @likes = @place.likes
  end

  def show
    @place = Place.find(params[:id])
    @likes = @place.likes
    @users = User.all
    @locations = @users.map(&:locations).flatten
    @frequency = location_frequency(@locations)
    @likes_by_cities = likes_by(:city)
    @likes_by_states = likes_by(:state)
    @likes_by_countries = likes_by(:country)
  end

  def create
    #   Place.find_or_create_by(
    #   name: params[:place][:name],
    #   address: params[:place][:address],
    #   phone_number: params[:place][:phone_number],
    #   category: params[:place][:category]
    #   )
    redirect_to admin_places_path
  end

  def delete
    @place = Place.find(params[:id])
    @place.destroy
    flash[:success] = 'Place deleted'
    redirect_to admin_places_path
  end

  def destroy
    @place = Place.find(params[:id])
    @place.destroy
    flash[:success] = 'Place deleted'
    redirect_to admin_places_path
  end

  def location_frequency(locations)
    {}.tap do |locations_by_frequency|
      locations.each do |location|
        location_city = location.city.to_s
        location_state = location.state.to_s
        location_country = location.country.to_s

        location_name = "#{location.city}, #{location.state} #{location.country}"
        if locations_by_frequency[location_city]
          locations_by_frequency[location_city] += 1
        else
          locations_by_frequency[location_city] = 1
        end
        if locations_by_frequency[location_state]
          locations_by_frequency[location_state] += 1
        else
          locations_by_frequency[location_state] = 1
        end
        if locations_by_frequency[location_country]
          locations_by_frequency[location_country] += 1
        else
          locations_by_frequency[location_country] = 1
        end
      end
    end
  end

  private

  def likes_by(geography)
    @place.locations.group_by(&geography).map do |group, locations|
      next if group.blank?

      {
        name: group,
        likes: locations.count
      }
    end.compact.sort_by do |group|
      group[:likes]
    end.reverse
  end

  def authenticate_admin!
    authenticate_user!
    redirect_to root_path, status: :forbidden unless current_user.admin?
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: %i[create edit update]

  def index
    @places = if params[:search].present?
                Place.perform_search(params[:search])
              else
                Place.all.order(name: :asc)
              end
    @place = Place.new
  end

  def show
    @place = Place.find(params[:id])
    @likes = @place.likes
    @users = User.all
    @locations = @users.map(&:locations).flatten
    # @frequency = location_frequency(@locations)
    @likes_by_cities = likes_by(:city)
    @likes_by_states = likes_by(:state)
    @likes_by_countries = likes_by(:country)
  end

  def likes
    @place = Place.find(params[:id])
    @likes = @place.likes
    @likes_by_cities = likes_by(:city)
    @likes_by_states = likes_by(:state)
    @likes_by_countries = likes_by(:country)
  end

  def update; end

  def edit; end

  def new
    @place = Place.new
  end

  def create
    if already_added?
      flash[:notice] = 'This restaurant has already been added!'
    else
      Place.find_or_create_by(
        name: params[:place][:name],
        address: params[:place][:address],
        phone_number: params[:place][:phone_number],
        category: params[:place][:category]
      )
      flash[:notice] = 'You have successfully added this restaurant to Food Mapp!'
    end
    redirect_to places_path
  end

  # def location_frequency(locations)
  #   {}.tap do |locations_by_frequency|
  #     locations.each do |location|
  #       location_city = "#{location.city}"
  #       location_state = "#{location.state}"
  #       location_country = "#{location.country}"

  #        location_name = "#{location.city}, #{location.state} #{location.country}"
  #         if locations_by_frequency[location_city]
  #          locations_by_frequency[location_city] += 1
  #         else
  #          locations_by_frequency[location_city]= 1
  #         end
  #         if locations_by_frequency[location_state]
  #          locations_by_frequency[location_state] += 1
  #         else
  #          locations_by_frequency[location_state]= 1
  #         end
  #         if locations_by_frequency[location_country]
  #          locations_by_frequency[location_country] += 1
  #         else
  #          locations_by_frequency[location_country]= 1
  #         end
  #     end
  #   end
  # end

  private

  def already_added?
    Place.where(id: params[:id]).exists?
  end

  def likes_by(geography)
    @place.locations.group_by(&geography).map do |group, locations|
      next if group.blank?

      {
        name: group,
        likes: locations.count
      }
    end.compact.sort_by do |group|
      group[:likes]
    end.reverse
  end
end

app/helpers/admin/places_helper.rb
module Admin::PlacesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/edit.html.erb
<h1>Places#edit</h1>
<p>Find me in app/views/places/edit.html.erb</p>

app/views/places/index.html.erb
<!-- <hr class="my-4"> -->
<div class="row">
  <div class="col-sm-6">
    <div class="map_container w-50 ml-0 mr-0 mb-0 mt-0 position-fixed">
      <div id="map"></div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="card border-0 clearfix m-0">
      <div class="card-body mt-0">
       <% @places.each do |place| %>
        <h1 class="display-5 text-chicle"><%= place.name %></h1>
        <h5><%= place.address %></h5>
        <h5><%= place.phone_number %></h5>
        <h5>Category: <%= place.category %></h5>
        <h5 class= "text-primary"><%= place.likes.count %><%= (place.likes.count) == 1 ? ' Like' : ' Likes'%></h5>
        <h5> <%# place.locations %></h5>
        <%# image_tag place.image.variant(resize: "200x300") %>
        <a><%= link_to "More Info", place_path(place), class: "btn btn-danger btn-lg"%></a><br><br><br>
        <% end %>
      </div>
    </div>
  </div>
</div>
<script>
  var places = <%== @places.map { |place| {lat: place.latitude, lng: place.longitude, name: place.name, address: place.address, likes: place.likes.count, id: place.id }}.to_json %>;

  var map;

  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 34.8526, lng: -82.3940},
      zoom: 11
    });
    
    places.forEach(function(place) {
      var position = new google.maps.LatLng(place.lat, place.lng);
      var marker = new google.maps.Marker({
        position: position,
        map: map,
        title: place.name
      });

      var content = place.name + place.likes

      var infowindow = new google.maps.InfoWindow({
          content: content
      });
      marker.addListener('click', function() {
          infowindow.open(map, marker);
      });
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=GOOGLE_MAPS_API&callback=initMap" async defer></script>

app/views/places/likes.html.erb
<!-- <hr class="my-4"> -->
<div class="map_container w-50 h-50 ml-0 mr-0 mb-0 mt-0 position-fixed">
  <div id="map"></div>
</div>
<div class="card mb-3 border-0 mb-0">
  <div class="card-body mt-0">
    <h1 class="display-3 text-chicle"><%= @place.name %></h1>
    <h4><%= @place.address %></h4>
    <h4><%= @place.phone_number %></h4>
    <h4>Category: <%= @place.category %></h4>
    <h4 class= "text-primary"><%= @place.likes.count %><%= (@place.likes.count) == 1 ? ' Like' : ' Likes'%></h4>
    <a><%= button_to 'Like', place_likes_path(@place), method: :post, class: "btn btn-success btn-lg w-50 font-weight-bold" %></a><br><br>
    <h1 class="display-4 text-chicle">Likes by Cities</h1>
      <ol>
        <% @likes_by_cities.each do |group| %>
          <h4><li><%= "#{group[:name]} = #{group[:likes]} Likes" %></li></h4>
        <% end %>
      </ol>
    <h1 class="display-4 text-chicle">Likes by States</h1>
      <ol>
        <% @likes_by_states.each do |group| %>
          <h4><li><%= "#{group[:name]} = #{group[:likes]} Likes" %></li></h4>
        <% end %>
      </ol>
    <h1 class="display-4 text-chicle">Likes by Countries</h1>
      <ol>
        <% @likes_by_countries.each do |group| %>
          <h4><li><%= "#{group[:name]} = #{group[:likes]} Likes" %></li></h4>
        <% end %>
      </ol>
  </div>
</div>

<script>
  var likes = <%== @likes.map { |like| {lat: like.latitude, lng: like.longitude }}.to_json %>;

  // var name = <%# @places.map { |place| {name: place.name}}.to_json %>;
  
  var map;

  // var content = <%# @places.map { |place| {name: place.name, likes: place.likes.count}}.to_json %>;

  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: 0, lng: 0},
      zoom: 2
    });

    places.forEach(function(place) {
      var position = new google.maps.LatLng(like.lat, like.lng);
      var marker = new google.maps.Marker({
        position: position,
        map: map,
        title: name
      });
      // var infowindow = new google.maps.InfoWindow({
      //     content: content
      // });
      // marker.addListener('click', function() {
      //     infowindow.open(map, marker);
      // });
    });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=GOOGLE_MAPS_API&callback=initMap" async defer></script>

app/views/places/new.html.erb
<div class= "container">
  <div class="row">
    <div class="col-sm-6">
      <div class= "card border-0">
        <div class= "card-body mt-4">
          <h1 class="text-chicle">Add a Restaurant to Food Mapp</h1>
          <%= simple_form_for @place do |f| %>
            <%= f.input :name, label: "Name of Restaurant:" %>
            <%= f.input :address, label: "Restaurant's Address:", placeholder: "123 Street, City, State Zip" %>
            <%= f.input :phone_number, label: "Phone Number:", placeholder: "(555) 555-5555" %>
            <%= f.input :category, label: "Category:", placeholder: "American, Casual, etc." %>
            <a><%= f.button :submit, label: "Add Restaurant", class: "btn btn-danger btn-lg w-50" %></a>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class= "card border-0 shadow mt-4">
        <div class= "card-body">
          <%= image_tag "jakub-kapusnak-296881-unsplash.jpg", size: "515x400" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-sm-6">
      <h2 class="text-chicle display-4"><%= @place.name %></h2>
      <div id="likes_map"></div>
      <div id="show_map"></div>
    </div>
    <div class="col-sm-6">
      <div class="card clearfix mt-5 mb-5">
        <div class="card-body mt-0">
          <a><%= button_to 'Like', place_likes_path(@place), method: :post, class: "btn btn-success btn-lg w-25 mb-2 font-weight-bold" %></a>
          <h6><%= @place.address %></h6>
          <h6><%= @place.phone_number %></h6>
          <h6>Category: <%= @place.category %></h6>
          <h5 class= "text-primary"><%= @place.likes.count %> <%= likes_unit @place.likes.count %></h5>
        </div>
      </div>
      <div class="card clearfix mt-5 mb-5">
        <div class="card-header">
          <h2 class="text-chicle display-5">Liked most by users from</h2>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-sm-4">
              <div class="">
              <h2 class="text-chicle display-6">City</h2>
                <ul class="list-unstyled">
                  <% @likes_by_cities.each do |group| %>
                    <h6><li><%= "#{group[:name]} = #{group[:likes]} #{likes_unit(group[:likes])}" %> </li></h6>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="">
              <h2 class="text-chicle display-6">State</h2>
                <ul class="list-unstyled">
                  <% @likes_by_states.each do |group| %>
                    <h6><li><%= "#{group[:name]} = #{group[:likes]} #{likes_unit(group[:likes])}" %></li></h6>
                  <% end %>
                </ul>
              </div>
            </div>
            <div class="col-sm-4">
              <div class="">
              <h2 class="text-chicle display-6">Country</h2>
                <ul class="list-unstyled">
                  <% @likes_by_countries.each do |group| %>
                    <h6><li><%= "#{group[:name]} = #{group[:likes]} #{likes_unit(group[:likes])}" %></li></h6>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  var place = <%== {lat: @place.latitude, lng: @place.longitude, name: @place.name, likes: @place.likes.count, address: @place.address }.to_json %>;
  var likeLocations = <%== @place.locations.map {|location| {lat: location.latitude, lng: location.longitude, address: location.address }}.to_json %>;

  var map;
  var likesMap;

  function initMap() {
    // place's map
    map = new google.maps.Map(document.getElementById('show_map'), {
      center: {lat: place.lat, lng: place.lng},
      zoom: 15
    });
    var name = <%== {name: @place.name}.to_json %>;
    var content = <%== {name: @place.name}.to_json %>;
    var position = new google.maps.LatLng(place.lat, place.lng);
    var marker = new google.maps.Marker({
      position: position,
      map: map,
      title: place.name
    });
    var infowindow = new google.maps.InfoWindow({
          content: place.name + place.address + place.likes
    });
    marker.addListener('click', function() {
        infowindow.open(map, marker);
    });

    // likes map
    likesMap = new google.maps.Map(document.getElementById('likes_map'), {
      zoom: 5,
      center: {lat: place.lat, lng: place.lng}
    });

    var icon = {
        url: "<%= asset_url 'like-icon.png' %>", // url
        scaledSize: new google.maps.Size(30, 30), // scaled size
        origin: new google.maps.Point(0,0), // origin
        anchor: new google.maps.Point(0, 0) // anchor
    };

    likeLocations.forEach(function(likeLocation){
      var position = new google.maps.LatLng(likeLocation.lat, likeLocation.lng);
      var marker = new google.maps.Marker({
        position: position,
        map: likesMap,
        title: likeLocation.name,
        icon: icon
      });
    })

    // var infowindow = new google.maps.InfoWindow({
    //       content: place.name + place.address + place.likes
    // });
    // marker.addListener('click', function() {
    //     infowindow.open(map, marker);
    // });
  }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=GOOGLE_MAPS_API&callback=initMap" async defer></script>

app/views/places/update.html.erb
<h1>Places#update</h1>
<p>Find me in app/views/places/update.html.erb</p>